In [1]:
import numpy as  np

In [ ]:
np.__version__

'2.4.0'

In [3]:
list1 = [1,2,3]
array1 = np.array([1,2,3])

In [4]:
type(array1)

numpy.ndarray

In [5]:
array_result = array1 ** 2
array_result

array([1, 4, 9])

1D Array

In [ ]:
marks_1d  = np.array((85, 90, 78))
marks_1d

1

2D Array

In [ ]:
marks_2d = np.array([[85, 90, 78], [88, 92, 80]])
marks_2d

array([[170, 180, 156],
       [176, 184, 160]])

3D Array

In [36]:
marks_3d = np.array([[[85, 90], [78, 88]],[[92, 80], [70, 60]]])
marks_3d.ndim
marks_3d.shape

(2, 2, 2)

In [17]:
np.zeros((2,3))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.zeros((2))

array([0., 0.])

In [22]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [24]:
np.arange(1,10, 2)

array([1, 3, 5, 7, 9])

In [27]:
np.linspace(0,100, 4)

array([  0.        ,  33.33333333,  66.66666667, 100.        ])

In [30]:
arr = np.array([1, 2, 3])
arr.dtype

dtype('int64')

Array indexing and slicing

In [ ]:
arr = np.array([10, 20, 30, 40])
arr[-2]

np.int64(30)

In [42]:
arr[2] = 50
arr

array([10, 20, 50, 40])

In [44]:
marks_2d = np.array([[85, 90, 78], [88, 92, 80]])
marks_2d[1,0]

np.int64(88)

In [ ]:
marks_3d = np.array([[[85, 90], [78, 88]],[[92, 80], [70, 60]]])
marks_3d[1, 0, 1]

np.int64(80)

Slicing Array

In [ ]:
arr = np.array([10,20,30,40,50,60])
arr[1:5]

array([20, 40, 60])

In [53]:
arr[1:4:2]

array([20, 40])

In [57]:
arr[::-2]

array([60, 40, 20])

In [58]:
matrix = np.array([
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ])

matrix[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [59]:
matrix[0:2, 0:2]

array([[1, 2],
       [4, 5]])

Boolean Indexing

In [62]:
arr = np.array([10,20,30,40,50,60])
arr>40

array([False, False, False, False,  True,  True])

In [63]:
print(arr[arr>40])

[50 60]


Fancy Indexing

In [ ]:
arr = np.array([10,20,30,40,50,60])
indices = [0,2,4]
print(arr[indices])

[10 30 50]


Element wise arithmetic operation

In [ ]:
store1 = np.array([100, 150, 200])
store2 = np.array([90, 160, 210])

# works only if size and shape of the matrix is same

print("Add: ", store1 + store2)
print("Subtract: ", store1 - store2)
print("Multiply: ", store1 * store2)
print("Divide: ", store1 / store2)

Add:  [190 310 410]
Subtract:  [ 10 -10 -10]
Multiply:  [ 9000 24000 42000]
Divide:  [1.11111111 0.9375     0.95238095]
